### ISSUE TITLE
Different sun angle values at 90°S (and north, so at the poles?)

### ISSUE THREAD

**Issue by Macintosh-Fan** [jpb10/SolarCalculator#23] opened 2023-03-09 22:32 UTC
The accuracy of the azimuth value is fine, but it isn't for the altitude, and this problem seems to only occur at the poles or so.

Location is `90°S` and `0°E`.
Time is 23:53:46 UTC on March 22, 2023 (`1679529226`)

```cpp
#include <iostream>

#include "SolarCalculator.h"

int main() {
    double az, el;

    time_t time = 1679529226;
    calcHorizontalCoordinates(time, -90.0, 0.0, az, el);
    std::cout << "Azimuth: " << az << "\nElevation: " << el << '\n';

    return 0;
}
```

Program output
<img width="162" alt="image" src="https://user-images.githubusercontent.com/50642934/224173825-8c2092ef-92fd-490e-a704-02d85a3972f4.png">

timeanddate.com (https://www.timeanddate.com/astronomy/night/@-90,0) (displayed time is UTC+13)
<img width="1169" alt="image" src="https://user-images.githubusercontent.com/50642934/224173707-18cdbee1-3352-4f19-a0b9-3bcfb1aa1222.png">

**Comment by Macintosh-Fan** [comment] 2023-03-09 22:43
It could be a general error, but more noticeable at the poles...

This was me just measuring it not too long ago. (The time thing in the terminal is me adding my own time display functionality.)
<img width="1510" alt="image" src="https://user-images.githubusercontent.com/50642934/224176834-0540c303-971e-4586-bb75-b90a1309bf6f.png">

**Comment by Macintosh-Fan** [comment] 2023-03-10 02:35
The problem is that the website and the program take refraction into account. So, either the website is wrong or there is a little bug here.

**Comment by jpb10** [comment] 2023-03-10 03:30
The website uses a different refraction model, and SolarCalculator doesn't take refraction into account below the visible horizon. So it doesn't make sense to compare apparent elevations below it.

**Comment by jpb10** [comment] 2023-03-10 03:32
Since the program behaves as intended, I will close this issue.

**Closed by jpb10** 2023-03-10 03:32 UTC
